### ISSUE TITLE
Some more URL rewrite to mimic github pages (and jekyll) behaviour

### ISSUE THREAD

**Issue by thibaultduponchelle** [symkat/MarkdownSite#2]
First thank you for this, it's damn cool! 👍🏼 

When linking between jekyll (and hugo) generated website, it's usual to use `/page/` or `page`. It's more a github pages rewrite rule than a jekyll thing actually.

If I take a jekyll example, here is what I observe:
1. When permalink is set to `page/` it will generate a `page/index.html` directory and link it with `page/`
2. When permalink is set to `page` it will generate a `page.html` and link it with `page`
3. When permalink is not set, it will generate a `page.html` and link it with `page.html`

Example of 1. with [about.md](https://github.com/thibaultduponchelle/jekyll-gh-pages-rewrite-dir-to-html/blob/master/about.md?plain=1) producing [about/index.html](https://github.com/thibaultduponchelle/jekyll-gh-pages-rewrite-dir-to-html/blob/master/public/about/index.html) and linked via [about/](https://thibaultduponchelle.github.io/jekyll-gh-pages-rewrite-dir-to-html/about/)

Example of 2. with [contact.md](https://github.com/thibaultduponchelle/jekyll-gh-pages-rewrite-dir-to-html/blob/master/contact.md?plain=1) producing [contact.html](https://github.com/thibaultduponchelle/jekyll-gh-pages-rewrite-dir-to-html/blob/master/public/contact.html) and linked via [contact](https://thibaultduponchelle.github.io/jekyll-gh-pages-rewrite-dir-to-html/contact)

Example of 3. with [nopermalink.md](https://github.com/thibaultduponchelle/jekyll-gh-pages-rewrite-dir-to-html/blob/master/nopermalink.md?plain=1) producing [nopermalink.html](https://github.com/thibaultduponchelle/jekyll-gh-pages-rewrite-dir-to-html/blob/master/public/nopermalink.html) and linked via [nopermalink.html](https://thibaultduponchelle.github.io/jekyll-gh-pages-rewrite-dir-to-html/nopermalink.html)

The current behaviour of MarkdownSite is like this (as [documented](https://markdownsite.com/docs)):
1. It is working fine for [about/](https://8bkghhuv.markdownsite.net/about/) and [about/index.html](https://8bkghhuv.markdownsite.net/about/index.html)
2. It is not working for [contact](https://8bkghhuv.markdownsite.net/contact) (but file is well there and accessible with [contact.html](https://8bkghhuv.markdownsite.net/contact.html))
3. It is working for [nopermalink.html](https://8bkghhuv.markdownsite.net/nopermalink.html)

Would it be possible to add some rewrite rules to lighttpd conf to hande 2.?

It would help to do not have to adapt too much when switching from jekyll/hugo to MarkdownSite 😃

**Comment by symkat** [comment]
Thanks!  I'm happy you like it, and thank you for the issues you've opened, they're very appreciated.

This is an area I'm going to need to think a little bit about how to address.  In the interim, I've written up docs on how to install a webserver in isolation and how it works right now.  You can see this document here: https://github.com/symkat/MarkdownSite/tree/master/docs/dev

I'll think on this some, as it does need to change.

**Comment by thibaultduponchelle** [comment]
(Seems fixed now 😃)

**Comment by symkat** [comment]
I believe this should all be fixed up now.  Yesterday the static routes were working much better, and that likely addressed the extent of your issues with it.  Some of the Markdown processing stuff had still been working not quite right.

This should overall be addressed in these changes:

https://github.com/symkat/MarkdownSite/commit/0bfbf5734b0f82b126f0e2331e94bc7fb76dcd64

https://github.com/symkat/MarkdownSite/commit/a705c9c5cface097a1f3b8f0df1688e1ef210b76

https://github.com/symkat/MarkdownSite/commit/bd8d61766b5b1205051aa82429a4f7410a3c8980

https://github.com/symkat/MarkdownSite/commit/600809912fb96e79c228e61f9d91bdca7ed3b5cb

https://github.com/symkat/MarkdownSite/commit/c563cca7e1d354ad55ab0892145c0930fa1ad000

Thank you for taking the time to open the issues and pull requests, don't hesitate to again if you run into anything else!

**Comment by thibaultduponchelle** [comment]
Thank you a lot!! 😃 👍🏼
