### ISSUE TITLE
[feature] Print commit hash in build log

### ISSUE THREAD

**Issue by thibaultduponchelle** [symkat/MarkdownSite#3]
I don't see anywhere the commit hash of what is built in the logs, would it be possible to add it? 

Thank you in advance

**Comment by symkat** [comment]
Thank you for the suggestion!

It will now display the output of `git log -1` while building.

I've added a few other bits, in this commit: https://github.com/symkat/MarkdownSite/commit/f1262ebe1648b6d772dbb0c6728d067f51855aae and the change is now live on MarkdownSite.
